### ISSUE TITLE
Testing jsrsasign with Google Wycheproof?

### ISSUE THREAD

**Issue by adonoho** [kjur/jsrsasign#223]
Urushima-san,

Google recently released [Project Wycheproof](https://security.googleblog.com/2016/12/project-wycheproof.html). As a crypto testing framework, it might provide some value in confirming that jsrsasign.js is as solid as well all think it is. Any thoughts on whether you might test jsrsasign against these tests?

Anon,
Andrew

**Comment by kjur** [comment]
I've taken a look wycheproof and found that it can be applied only for Java crypto library. So please let me know if it can be applied to JavaScript. Thanks.

**Comment by thaidn** [comment]
Hey I'm a developer of Wycheproof. You can use it to test Javascript library because most of the tests are provided as test vectors. For example we're using it to test WebCrypto implementations: https://github.com/google/wycheproof/tree/master/javascript.

Please drop me a line at thaidn@gmail.com if you need further help.

**Comment by kjur** [comment]
@thaidn Thank you for the link.
