### ISSUE TITLE
How to ONLY import or require JWS/JWT

### ISSUE THREAD

**Issue by tychong82** [kjur/jsrsasign#348]
Seems like when I import just the JWS, it is also including all the others as well. Is it possible to just import JWS? My bundle size is quite big.

`import { jws } from 'jsrsasign';`

**Comment by brockallen** [comment]
I just had to do my own custom build of jsrsasign for this to work: 

https://github.com/IdentityModel/oidc-client-js/commit/b451417bc24b258c87363c61e543f9b3f53b83d9

then i filtered the modules not needed for JWT validation:
https://github.com/IdentityModel/oidc-client-js/commit/dfd4fa8b6a8fa83a62c96be2a2978fd285361aa1

**Comment by kjur** [comment]
@tychong82 , you can minimize the size of codes by choosing methods and functions of jsrsasign. Otherwise, you can consider to use subset package.
https://github.com/kjur/jsrsasign/wiki/NOTE-jsrsasign-subset-package

**Comment by fnagel** [comment]
Can somebody help me out how to do this in TypeScript? I have this: `import { KJUR, KEYUTIL, b64utoutf8, RSAKey } from 'jsrsasign'`

I've played around with `compilerOptions` and `paths` configuration in `tsconfig.ts` but without success. Any ideas?

**Comment by kjur** [comment]
Hi @fnagel , how about this page:

https://gist.github.com/aneilbaboo/2e0e90cdbfb44505405fd07c29382225

**Comment by fnagel** [comment]
Hey @kjur! Thanks for your answer!

Mhhh, when using the full package types are no problem due to @types/jsrsasign but when importing the subset using `import { KJUR, KEYUTIL, b64utoutf8 } from 'jsrsasign/lib/jsrsasign-jwths-min.js'` I had to create a dummy declaration with `declare module 'jsrsasign/lib/jsrsasign-jwths-min.js'`.
Sadly, this does not work. Following error pops up when using `KJUR.jws.JWS.verifyJWT()`: `TypeError: jsrsasign_lib_jsrsasign_jwths_min_js__WEBPACK_IMPORTED_MODULE_11__.KJUR is undefined`
