### ISSUE TITLE
RSAKey is not defined in jsrsasign-jwths-min.js

### ISSUE THREAD

**Issue by dome4** [kjur/jsrsasign#452]
In the subset package **jsrsasign-jwths-min.js** a definition of the class / function RSAKey is missing. Thus, if you for example try to execute `KJUR.jws.JWS.verifyJWT()` the instance type check which is commonly used results in an error: `a instance of RSAKey`.

**Comment by kjur** [comment]
" jsrsasign-jwths-min.js" only supports "HS*" signatures. If you need "RS*" signatures, please use "jsrsasign-all-min.js". Thanks.

**Comment by joanbm** [comment]
This seems to be a problem even with HS* tokens. For example...

Works:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/10.1.4/jsrsasign-all-min.js" type="text/javascript"></script>
<script>
console.log(KJUR.jws.JWS.verify("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImp0aSI6IjE3NjU4OGY3LWZkZGItNDcxNi05ZTFkLTdhN2I1NjE4ZjIzOCIsImlhdCI6MTYxMDEwMjcxNCwiZXhwIjoxNjEwMTA2MzE0fQ.hv9GTjZHgxCk4rfoFaj79vn40OsvtpG0MxOhYZZYAjI", "736563726574"));
</script>
```

Doesn't work: "Uncaught ReferenceError: RSAKey is not defined"
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/10.1.4/jsrsasign-jwths-min.js" type="text/javascript"></script>
<script>
console.log(KJUR.jws.JWS.verify("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImp0aSI6IjE3NjU4OGY3LWZkZGItNDcxNi05ZTFkLTdhN2I1NjE4ZjIzOCIsImlhdCI6MTYxMDEwMjcxNCwiZXhwIjoxNjEwMTA2MzE0fQ.hv9GTjZHgxCk4rfoFaj79vn40OsvtpG0MxOhYZZYAjI", "736563726574"));
</script>
```

Works? (hack, please don't do this):
```html
<script>RSAKey=0;</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrsasign/10.1.4/jsrsasign-jwths-min.js" type="text/javascript"></script>
<script>
console.log(KJUR.jws.JWS.verify("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImp0aSI6IjE3NjU4OGY3LWZkZGItNDcxNi05ZTFkLTdhN2I1NjE4ZjIzOCIsImlhdCI6MTYxMDEwMjcxNCwiZXhwIjoxNjEwMTA2MzE0fQ.hv9GTjZHgxCk4rfoFaj79vn40OsvtpG0MxOhYZZYAjI", "736563726574"));
</script>
```

The problematic piece of code appears to be this one:
https://github.com/kjur/jsrsasign/blob/40bc07c861f078b4a8e1212a78cc0ce80041182f/src/jws-3.3.js#L403

The problem is that if RSAKey is not defined, then `typeof RSAKey` is `"undefined"` (string) and not `undefined`.

(Apologies if this is a misuse of the library and not a real problem, I've just been testing the library for a few minutes)
