### ISSUE TITLE
Question: Verify signed jsrsasign string with bouncy castle

### ISSUE THREAD

**Issue by Julchenwsf** [kjur/jsrsasign#486]
Hello,
i want to verify my generated signature hex value with javas bouncy castle. But this framework expected a byte array. Do you have a function to convert the hexvalue to a bytearray. 

Thanks in advance.

Juli

**Comment by kjur** [comment]
How about use encoders of BouncyCastle JCE library:
https://stackoverflow.com/questions/45937975/how-to-convert-bouncy-castle-scrypt-byte-array-to-string-format-or-hexstring-for

Otherwise 
ByteUtils class of fromHexString or toHexString methods:
http://javadox.com/org.bouncycastle/bcprov-jdk15on/1.50/org/bouncycastle/pqc/math/linearalgebra/ByteUtils.html
