### ISSUE TITLE
readCertDER() needed for certificate creation

### ISSUE THREAD

**Issue by pprindeville** [kjur/jsrsasign#498]
I'm seeing a lot of places (like Google SafetyNet, WebAuthn, etc.) were certificates are marshaled either as header-less base64 or else as CBOR-marshaled binary, all suitable for DER parsing.

Indeed, even `readCertPEM()` is a degenerate case of stripping the header/trailer, applying base64 decoding, and squirting the resultant value into `readCertDER()` instead.

By analogy, `readCertHex()` is a trivial conversion of hex to binary, and squirting binary into `readCertDER()`.

**Comment by kjur** [comment]
Your analogy seems wrong because a DER binary data will be converted into a hexadecimal string then jsrsasign can handle it by readCertHex().

There are some way to represent binary in JavaScript such as raw string or ArrayBuffer. Jsrsasign provides rstrtohex() and ArrayBuffetohex(). 

I don't think readCertDER() is necessary at this point. If your request have 1,000 likes 👍 , I may implement readCertDER(for raw string or ArrayBuffer). (Since 70M+ npm downloads per month).

Once this ticket is closed and I'll wait 👍 likes.
