### ISSUE TITLE
Request to update jsrsasign npm module

### ISSUE THREAD

**Issue by anuchandy** [kjur/jsrsasign#94]
Hello @kjur looks like the 'jsrsasign' NPM module is not updated for last couple of years. I would like to use this npm module in one of the project. Could you please help updating the npm module https://www.npmjs.com/package/jsrsasign

**Comment by adonoho** [comment]
@kjur,

Let me second this request for a likely slightly different reason. I suspect you haven't updated npm support because node.js now has a crypto library. jsrsasign would be redundant and unused.

In my case, I need a Javascript library that supports RSA-2048/SHA-256 signatures to run on Parse.com. Parse is "node-like". It is Google's V8 plus some, but not all, of node.js' libraries. In particular, they do not implement the digital signature part of the node.js crypto library. Their stated position is that I should get my signature support from a Javascript library.

Even though I am not a Node-ster, I'm an iOS developer, I am happy to help configure and debug this process. Parse.com accounts are free for development. I've tried the port of jsrsasign before and failed. I just don't know enough about the Javascript ecosystem to solve this problem. But with some guidance... I'm sure I could succeed and help make jsrassign better.

Anon,
Andrew, @adonoho

**Comment by kjur** [comment]
I've officially released npm module today.
https://www.npmjs.com/package/jsrsasign for jsrsasign 4.8.2.
Thanks
